### ISSUE TITLE
Did Web Resoluiton Internal Error

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/web5-rs#272]
In web5 core kt we cannot resolve a did web.

To reproduce
1. make a directory in a terminal with a `.well-known/did.json` file

```
{
   "document":{
      "id":"did:web:www.tbd.website",
      "@context":[
         "https://www.w3.org/ns/did/v1"
      ],
      "verificationMethod":[
         {
            "id":"did:web:www.tbd.website#key-0",
            "type":"JsonWebKey",
            "controller":"did:web:www.tbd.website",
            "publicKeyJwk":{
               "alg":"Ed25519",
               "kty":"OKP",
               "crv":"Ed25519",
               "x":"gNFtgCZhOYv00p48FHQYt4edkoBPOyw0oGAB20LrT0c"
            }
         }
      ]
   }
}
```

2. run `http-server -p 1234`

3. run these tests and you will get these errros:

```
    @Test
    fun `can create did web from uri`() = runBlocking {
        val didUri = "did:web:localhost:1234"
        val resolvedDid = DidWeb(didUri)

        assertEquals("did:web:localhost:1234", resolvedDid.document!!.id)
    }
    

@Test `can resolve did web` {
 val didWebResolutionResult = DidWeb.resolve("did:web:localhost:1234")
 }

```

/Users/nealr/.gradle/jdks/eclipse_adoptium-21-aarch64-os_x/jdk-21+35/Contents/Home/bin/java -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=65370:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /Users/nealr/.m2/repository/org/junit/platform/junit-platform-launcher/1.10.2/junit-platform-launcher-1.10.2.jar:/Users/nealr/.m2/repository/org/junit/platform/junit-platform-engine/1.10.2/junit-platform-engine-1.10.2.jar:/Users/nealr/.m2/repository/org/junit/vintage/junit-vintage-engine/5.10.2/junit-vintage-engine-5.10.2.jar:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit5-rt.jar:/Applications/IntelliJ IDEA.app/Contents/plugins/junit/lib/junit-rt.jar:/Users/nealr/MY-WORKSPACE/WEB5-RS/web5-rs/bound/kt/target/test-classes:/Users/nealr/MY-WORKSPACE/WEB5-RS/web5-rs/bound/kt/target/classes:/Users/nealr/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.9.22/kotlin-stdlib-jdk8-1.9.22.jar:/Users/nealr/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.9.22/kotlin-stdlib-1.9.22.jar:/Users/nealr/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/Users/nealr/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.9.22/kotlin-stdlib-jdk7-1.9.22.jar:/Users/nealr/.m2/repository/net/java/dev/jna/jna/5.12.0/jna-5.12.0.jar:/Users/nealr/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.8.0/kotlinx-coroutines-core-1.8.0.jar:/Users/nealr/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.8.0/kotlinx-coroutines-core-jvm-1.8.0.jar:/Users/nealr/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.17.0/jackson-databind-2.17.0.jar:/Users/nealr/.m2/repository/net/bytebuddy/byte-buddy/1.14.9/byte-buddy-1.14.9.jar:/Users/nealr/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.17.0/jackson-core-2.17.0.jar:/Users/nealr/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.17.0/jackson-annotations-2.17.0.jar:/Users/nealr/.m2/repository/com/fasterxml/jackson/module/jackson-module-kotlin/2.17.0/jackson-module-kotlin-2.17.0.jar:/Users/nealr/.m2/repository/org/jetbrains/kotlin/kotlin-reflect/1.7.22/kotlin-reflect-1.7.22.jar:/Users/nealr/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.10.2/junit-jupiter-api-5.10.2.jar:/Users/nealr/.m2/repository/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar:/Users/nealr/.m2/repository/org/junit/platform/junit-platform-commons/1.10.2/junit-platform-commons-1.10.2.jar:/Users/nealr/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar:/Users/nealr/.m2/repository/io/mockk/mockk-jvm/1.13.11/mockk-jvm-1.13.11.jar:/Users/nealr/.m2/repository/io/mockk/mockk-dsl-jvm/1.13.11/mockk-dsl-jvm-1.13.11.jar:/Users/nealr/.m2/repository/io/mockk/mockk-agent-jvm/1.13.11/mockk-agent-jvm-1.13.11.jar:/Users/nealr/.m2/repository/org/objenesis/objenesis/3.3/objenesis-3.3.jar:/Users/nealr/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.6/byte-buddy-agent-1.14.6.jar:/Users/nealr/.m2/repository/io/mockk/mockk-agent-api-jvm/1.13.11/mockk-agent-api-jvm-1.13.11.jar:/Users/nealr/.m2/repository/io/mockk/mockk-core-jvm/1.13.11/mockk-core-jvm-1.13.11.jar:/Users/nealr/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.9.10/kotlin-stdlib-common-1.9.10.jar:/Users/nealr/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/Users/nealr/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/Users/nealr/.m2/repository/org/junit/jupiter/junit-jupiter/5.8.2/junit-jupiter-5.8.2.jar:/Users/nealr/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.8.2/junit-jupiter-params-5.8.2.jar:/Users/nealr/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.8.2/junit-jupiter-engine-5.8.2.jar:/Users/nealr/.m2/repository/org/junit/platform/junit-platform-engine/1.8.2/junit-platform-engine-1.8.2.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit5 web5.sdk.dids.methods.web.DidWebTests,can create did web from uri

web5.sdk.rust.RustCoreException$Exception: type=web5::dids::methods::MethodError, variant=ResolutionError, msg=Something went wrong during DID resolution.

	at web5.sdk.rust.FfiConverterTypeRustCoreError.read(UniFFI.kt:6519)
	at web5.sdk.rust.FfiConverterTypeRustCoreError.read(UniFFI.kt:6514)
	at web5.sdk.rust.FfiConverter$DefaultImpls.liftFromRustBuffer(UniFFI.kt:193)
	at web5.sdk.rust.FfiConverterRustBuffer$DefaultImpls.liftFromRustBuffer(UniFFI.kt:205)
	at web5.sdk.rust.FfiConverterTypeRustCoreError.liftFromRustBuffer(UniFFI.kt:6514)
	at web5.sdk.rust.FfiConverterTypeRustCoreError.liftFromRustBuffer(UniFFI.kt:6514)
	at web5.sdk.rust.FfiConverterRustBuffer$DefaultImpls.lift(UniFFI.kt:206)
	at web5.sdk.rust.FfiConverterTypeRustCoreError.lift(UniFFI.kt:6514)
	at web5.sdk.rust.FfiConverterTypeRustCoreError.lift(UniFFI.kt:6514)
	at web5.sdk.rust.RustCoreException$ErrorHandler.lift(UniFFI.kt:6508)
	at web5.sdk.rust.RustCoreException$ErrorHandler.lift(UniFFI.kt:6507)
	at web5.sdk.rust.UniFFIKt.uniffiCheckCallStatus(UniFFI.kt:269)
	at web5.sdk.rust.UniFFIKt.access$uniffiCheckCallStatus(UniFFI.kt:1)
	at web5.sdk.rust.UniFFIKt.uniffiRustCallAsync(UniFFI.kt:7019)
	at web5.sdk.rust.DidWeb$Companion.fromUri(UniFFI.kt:2956)
	at web5.sdk.dids.methods.web.DidWeb$rustCoreDidWeb$1.invokeSuspend(DidWeb.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at web5.sdk.dids.methods.web.DidWeb.<init>(DidWeb.kt:32)
	at web5.sdk.dids.methods.web.DidWebTests$can create did web from uri$1.invokeSuspend(DidWebTests.kt:31)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at web5.sdk.dids.methods.web.DidWebTests.can create did web from uri(DidWebTests.kt:29)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

Process finished with exit code 255

**Comment by nitro-neal** [comment]
thanks @andresuribe87 , we should actually be using this to test:
`did:web:localhost%3A1234`

```
 A port MAY be included and the colon MUST be percent encoded to prevent a conflict with paths
```

**Comment by nitro-neal** [comment]
solved and updated here
